---
name: Report

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest #-4-cores
    defaults:
      run:
        working-directory: reporting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up unused files
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/microsoft
          sudo rm -rf /opt/mssql-tools
          sudo rm -rf /usr/share/R
          sudo rm -rf /usr/share/X11
          sudo rm -rf /usr/share/apache-*
          sudo rm -rf /usr/share/java
          sudo rm -rf /usr/share/php*
          sudo rm -rf /usr/share/postgresq*
          sudo rm -rf /usr/share/sbt
          sudo rm -rf /usr/share/vim
          sudo rm -rf /usr/local/lib/lein
          sudo rm -rf /usr/local/lib/R

      - name: Log in to Github Package
        run: echo $GH_TOKEN | docker login ghcr.io -u jatautomoton --password-stdin
        env:
          GH_TOKEN: ${{secrets.GHP_ACCESS_TOKEN}}

      - name: Pull images
        run: docker compose pull

      - name: Generate report
        run: docker compose run -e UPLOAD -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e BUCKET --build tests
        # continue-on-error: true
        env:
          UPLOAD: "TRUE"
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_PROD_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_PROD_SECRET_ACCESS_KEY}}
          BUCKET: ${{secrets.AWS_PROD_BUCKET}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
